# Generated by Django 4.1.4 on 2022-12-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cctv",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("road_name", models.CharField(max_length=255, unique=True)),
                ("users", models.ManyToManyField(related_name="cctvs", to="user.user")),
            ],
        ),
    ]
